[package]
name = "rusty-chat-frontend"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.18"
yew-router = "0.15.0"
js-sys = "0.3.51"
wasm-bindgen = "0.2.74"
anyhow = "1.0.42"
serde = "1.0.126"
serde_json = "1.0.64"
