[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
